title: "Apollo Oil"
description: "Premium industrial lubricants for businesses across Ireland."
url: "https://localsacra.github.io"
baseurl: "/apollo-oil"

author:
  name: "Apollo Oil"
  email: "info@apollooil.ie"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site
  - .jekyll-cache